<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>C&#43;&#43;——异常 - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/d17cc48dff5de397b7e0a3205424b6a9/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="C&#43;&#43;——异常">
  <meta property="og:description" content="前言：本篇文章我们来分享C&#43;&#43;的一个全新内容——异常。
目录
一.异常概念
二.异常的使用
1.异常的抛出和匹配原则 2.在函数调用链中异常栈展开匹配原则
3.异常的重新抛出
三.异常的优缺点
1.优点
2.缺点
结语
一.异常概念 异常是一种处理错误的方式，当一个函数发现自己无法处理的错误时就可以抛出异常，让函数的直接或间接的调用者处理这个错误。
异常的使用包含以下三个关键字：
throw: 当问题出现时，程序会抛出一个异常。这是通过使用 throw 关键字来完成的。catch: 在您想要处理问题的地方，通过异常处理程序捕获异常.catch 关键字用于捕获异常，可以有多个catch进行捕获。try: try 块中的代码标识将被激活的特定异常,它后面通常跟着一个或多个 catch 块。 如果有一个块抛出一个异常，捕获异常的方法会使用 try 和 catch 关键字。try 块中放置可能抛出异常的代码，try 块中的代码被称为保护代码。使用 try/catch 语句的语法如下所示：
try
{
// 保护的标识代码
}catch( ExceptionName e1 )
{
// catch 块
}catch( ExceptionName e2 )
{
// catch 块
}catch( ExceptionName eN )
{
// catch 块
} 简单来说，就是try区域保护某些语句，当语句出现异常时，由throw抛出一个某种类型的异常对象，通过与多个catch语句的对象类型进行匹配，再执行catch中的语句。 二.异常的使用 1.异常的抛出和匹配原则 异常是通过抛出对象而引发的，该对象的类型决定了应该激活哪个catch的处理代码。被选中的处理代码是调用链中与该对象类型匹配且离抛出异常位置最近的那一个。 抛出异常对象后，会生成一个异常对象的拷贝，因为抛出的异常对象可能是一个临时对象，所以会生成一个拷贝对象，这个拷贝的临时对象会在被catch以后销毁。（这里的处理类似于函数的传值返回）catch(...)可以捕获任意类型的异常，问题是不知道异常错误是什么。实际中抛出和捕获的匹配原则有个例外，并不都是类型完全匹配，可以抛出的派生类对象使用基类捕获。 2.在函数调用链中异常栈展开匹配原则 首先检查throw本身是否在try块内部，如果是再查找匹配的catch语句。如果有匹配的，则调到catch的地方进行处理。没有匹配的catch则退出当前函数栈，继续在调用函数的栈中进行查找匹配的catch。如果到达main函数的栈，依旧没有匹配的，则终止程序。上述这个沿着调用链查找匹配的catch子句的过程称为栈展开。所以实际中我们最后都要加一个catch(...)捕获任意类型的异常，否则当有异常没捕获，程序就会直接终止。找到匹配的catch子句并处理以后，会继续沿着catch子句后面继续执行。 下面我们实战一下异常的使用：">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-08-03T18:27:35+08:00">
    <meta property="article:modified_time" content="2024-08-03T18:27:35+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">C&#43;&#43;——异常</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>前言：本篇文章我们来分享C++的一个全新内容——异常。</p> 
<hr> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="%E4%B8%80.%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5-toc" style="margin-left:0px;"><a href="#%E4%B8%80.%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5" rel="nofollow">一.异常概念</a></p> 
<p id="%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8-toc" style="margin-left:0px;"><a href="#%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8" rel="nofollow">二.异常的使用</a></p> 
<p id="%C2%A01.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99%C2%A0-toc" style="margin-left:40px;"><a href="#%C2%A01.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99%C2%A0" rel="nofollow"> 1.异常的抛出和匹配原则 </a></p> 
<p id="2.%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99-toc" style="margin-left:40px;"><a href="#2.%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99" rel="nofollow">2.在函数调用链中异常栈展开匹配原则</a></p> 
<p id="3.%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA-toc" style="margin-left:40px;"><a href="#3.%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA" rel="nofollow">3.异常的重新抛出</a></p> 
<p id="%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9-toc" style="margin-left:0px;"><a href="#%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9" rel="nofollow">三.异常的优缺点</a></p> 
<p id="1.%E4%BC%98%E7%82%B9-toc" style="margin-left:40px;"><a href="#1.%E4%BC%98%E7%82%B9" rel="nofollow">1.优点</a></p> 
<p id="2.%E7%BC%BA%E7%82%B9-toc" style="margin-left:40px;"><a href="#2.%E7%BC%BA%E7%82%B9" rel="nofollow">2.缺点</a></p> 
<p id="%E7%BB%93%E8%AF%AD-toc" style="margin-left:0px;"><a href="#%E7%BB%93%E8%AF%AD" rel="nofollow">结语</a></p> 
<hr> 
<h2 id="%E4%B8%80.%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5" style="background-color:transparent;">一.异常概念</h2> 
<p>异常是一种处理错误的方式，<strong>当一个函数发现自己无法处理的错误时就可以抛出异常，让函数的直接或间接的调用者处理这个错误</strong>。</p> 
<p>异常的使用包含以下三个关键字：</p> 
<ul><li><strong>throw: 当问题出现时，程序会抛出一个异常。这是通过使用 throw 关键字来完成的。</strong></li><li><strong>catch: 在您想要处理问题的地方，通过异常处理程序捕获异常.catch 关键字用于捕获异常，可以有多个catch进行捕获。</strong></li><li><strong>try: try 块中的代码标识将被激活的特定异常,它后面通常跟着一个或多个 catch 块。</strong></li></ul> 
<p>如果有一个块抛出一个异常，捕获异常的方法会使用 try 和 catch 关键字。try 块中放置可能抛出异常的代码，try 块中的代码被称为保护代码。使用 try/catch 语句的语法如下所示：</p> 
<blockquote> 
 <p>try<br> {<!-- --><br>   // 保护的标识代码<br> }catch( ExceptionName e1 )<br> {<!-- --><br>   // catch 块<br> }catch( ExceptionName e2 )<br> {<!-- --><br>   // catch 块<br> }catch( ExceptionName eN )<br> {<!-- --><br>   // catch 块<br> } </p> 
</blockquote> 
<p>简单来说，就是<strong><span style="background-color:#ffd900;">try区域保护某些语句，当语句出现异常时，由throw抛出一个某种类型的异常对象，通过与多个catch语句的对象类型进行匹配，再执行catch中的语句</span></strong>。 </p> 
<hr> 
<h2 id="%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8">二.异常的使用</h2> 
<h3 id="%C2%A01.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99%C2%A0"> 1.异常的抛出和匹配原则 </h3> 
<ol><li>异常是通过<strong>抛出对象</strong>而引发的，<strong>该对象的类型决定了应该激活哪个catch的处理代码</strong>。</li><li>被选中的处理代码是调用链中与该对象类型匹配且离抛出异常<strong>位置最近</strong>的那一个。</li><li> 抛出异常对象后，会生成一个<strong>异常对象的拷贝</strong>，因为抛出的异常对象可能是一个临时对象，所以会生成一个拷贝对象，这个拷贝的临时对象会在被catch以后销毁。（这里的处理类似于函数的传值返回）</li><li>catch(...)可以<strong>捕获任意类型的异常</strong>，问题是不知道异常错误是什么。</li><li>实际中抛出和捕获的匹配原则有个例外，并不都是类型完全匹配，可以<strong>抛出的派生类对象使用基类捕获</strong>。</li></ol> 
<h3 id="2.%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99">2.在函数调用链中异常栈展开匹配原则</h3> 
<ol><li>首先检查throw本身是否在try块内部，如果是再查找匹配的catch语句。如果有匹配的，则调到catch的地方进行处理。</li><li>没有匹配的catch则退出当前函数栈，继续在调用函数的栈中进行查找匹配的catch。</li><li>如果到达main函数的栈，依旧没有匹配的，则终止程序。上述这个沿着调用链查找匹配的catch子句的过程称为<strong>栈展开</strong>。所以实际中我们最后都要加一个catch(...)捕获任意类型的异常，否则当有异常没捕获，程序就会直接终止。</li><li>找到匹配的catch子句并处理以后，会继续沿着catch子句后面继续执行。</li></ol> 
<p>下面我们实战一下异常的使用：</p> 
<pre><code class="language-cpp">void Func()
{
	int a, b;
	cin &gt;&gt; a &gt;&gt; b;
	// 当b == 0时抛出异常
	if (b == 0)
		throw "Division by zero condition!";
	else if (a == 0)
		throw 1;
	else
		cout &lt;&lt; "no error" &lt;&lt; endl;
}
int main()
{
	try {
		Func();
	}
	catch (const char* errmsg)
		{
	cout &lt;&lt; errmsg &lt;&lt; endl;
		}
		catch (...) {
			cout &lt;&lt; "unkown exception" &lt;&lt; endl;
		}
		return 0;
}</code></pre> 
<p>可以看出，<strong>Func函数是我们要保护的语句</strong>，<strong><span style="background-color:#ffd900;">当b == 0时，我们认为出现异常，此时通过throw抛出一段字符串，当a == 0时，也认为出现异常，通过throw抛出1</span></strong>，catch进行字符串类型的匹配，以及对未知类型的匹配，三种结果如下：</p> 
<p>无异常：</p> 
<p><img alt="" height="128" src="https://images2.imgbox.com/59/7d/6gC4WEcw_o.png" width="326"></p> 
<p>有异常匹配字符串类型：</p> 
<p><img alt="" height="147" src="https://images2.imgbox.com/db/21/I0GUuNO7_o.png" width="324"></p> 
<p>有异常匹配未知类型：</p> 
<p><img alt="" height="141" src="https://images2.imgbox.com/2b/61/gIAzm2Et_o.png" width="330"></p> 
<hr> 
<h3 id="3.%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA">3.异常的重新抛出</h3> 
<p>有的时候，异常的抛出并不一定处于合理的位置，来看下面代码：</p> 
<pre><code class="language-cpp">void Func()
{
	int a, b;
	cin &gt;&gt; a &gt;&gt; b;

    int* array = new int[10];

	// 当b == 0时抛出异常
	if (b == 0)
		throw "Division by zero condition!";
	else if (a == 0)
		throw 1;
	else
		cout &lt;&lt; "no error" &lt;&lt; endl;

    cout &lt;&lt; "delete []" &lt;&lt; array &lt;&lt; endl;
    delete[] array;
}
</code></pre> 
<p>这里我们new了一个数组，但是在函数中，如果抛出了异常，函数是不会继续往下执行语句的，这样就到账我们的数组无法被释放。</p> 
<p>所以说这里我们捕获异常之后，并不去处理它，而是将其重新抛出去，具体操作为：</p> 
<pre><code class="language-cpp">void Func()
{
	int a, b;
	cin &gt;&gt; a &gt;&gt; b;

    int* array = new int[10];
    try
    {
	    // 当b == 0时抛出异常
	    if (b == 0)
		    throw "Division by zero condition!";
	    else if (a == 0)
		    throw 1;
	    else
		    cout &lt;&lt; "no error" &lt;&lt; endl;
    }catch(...)
    {
        cout &lt;&lt; "delete []" &lt;&lt; array &lt;&lt; endl;
        delete[] array;
        throw;
    }

    cout &lt;&lt; "delete []" &lt;&lt; array &lt;&lt; endl;
    delete[] array;
}
</code></pre> 
<hr> 
<h2 id="%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9">三.异常的优缺点</h2> 
<h3 id="1.%E4%BC%98%E7%82%B9">1.优点</h3> 
<ol><li>异常对象定义好了，相比错误码的方式可以清晰准确的展示出错误的各种信息，甚至可以包<br> 含堆栈调用的信息，这样可以帮助更好的定位程序的bug。</li><li>很多的第三方库都包含异常，比如boost、gtest、gmock等等常用的库，那么我们使用它们<br> 也需要使用异常。</li><li> 部分函数使用异常更好处理，比如构造函数没有返回值，不方便使用错误码方式处理。比如<br> T&amp; operator这样的函数，如果pos越界了只能使用异常或者终止程序处理，没办法通过返回值表示错误。</li></ol> 
<hr> 
<h3 id="2.%E7%BC%BA%E7%82%B9">2.缺点</h3> 
<ol><li>异常会导致程序的执行流乱跳，并且非常的混乱，并且是运行时出错抛异常就会乱跳。这会<br> 导致我们跟踪调试时以及分析程序时，比较困难。</li><li>异常会有一些性能的开销。当然在现代硬件速度很快的情况下，这个影响基本忽略不计。</li><li> C++没有垃圾回收机制，资源需要自己管理。有了异常非常容易导致内存泄漏、死锁等异常<br> 安全问题。这个需要使用RAII来处理资源的管理问题。学习成本较高。</li><li> C++标准库的异常体系定义得不好，导致大家各自定义各自的异常体系，非常的混乱。</li><li>异常尽量规范使用，否则后果不堪设想，随意抛异常，外层捕获的用户苦不堪言。所以异常<br> 规范有两点：一、抛出异常类型都继承自一个基类。二、函数是否抛异常、抛什么异常，都使用 func（） throw();的方式规范化。</li></ol> 
<p>总体而言，异常的利大于弊，所以在实践中还是非常支持去使用异常的。 </p> 
<hr> 
<h2 id="%E7%BB%93%E8%AF%AD">结语</h2> 
<p>关于异常就分享这么多，喜欢本篇文章记得一键三连，我们下期再见！</p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/37009d2d80c367b3dcafe5bd0174c807/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">GPT-4o mini模型：小型化AI解决方案的创新应用案例</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/1dfb595655a2741e9967b9a1f6f17c67/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">R 语言学习教程，从入门到精通，R的安装与环境的配置（3）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>