<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>【C&#43;&#43;进阶学习】第十二弹——C&#43;&#43; 异常处理：深入解析与实践应用 - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/849aa268a5bc8426f1442bda64429ac2/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="【C&#43;&#43;进阶学习】第十二弹——C&#43;&#43; 异常处理：深入解析与实践应用">
  <meta property="og:description" content="前言：
在C&#43;&#43;编程语言中，异常处理是一种重要的机制，它允许程序员在运行时捕获和处理错误或异常情况。本文将详细介绍C&#43;&#43;异常处理的相关知识点，包括异常的定义、抛出与捕获、异常处理的原则、以及在实际编程中的应用。
目录
1. 异常处理的基本概念
1.1 异常的定义
1.2 异常的抛出
1.3 异常的捕获
2. 异常的使用
2.1 异常抛出和匹配的原则
2.2 在函数调用链中异常栈的展开匹配原则
3. 异常的重新抛出
4. 异常安全
5. 异常规格
6. C&#43;&#43;异常处理的实践应用
6.1 文件操作异常
6.2 数学运算异常
7. 总结
1. 异常处理的基本概念 在C&#43;&#43;中，异常处理是一种机制，用于处理运行时发生的错误或异常情况。异常可以是程序执行过程中遇到的任何问题，如除以零、文件读写错误、资源未正确释放等。
1.1 异常的定义 在C&#43;&#43;中，异常是一个对象，通常由std::exception或其派生类创建。异常对象包含了错误信息和状态，程序员可以使用这些信息来诊断和处理错误。
1.2 异常的抛出 异常的抛出使用throw关键字。程序员在代码中使用throw语句来抛出异常，这可以是显式抛出一个异常对象，也可以是抛出一个特定类型的异常（如std::runtime_error）。
throw std::runtime_error(&#34;发生了一个错误&#34;); 1.3 异常的捕获 异常的捕获使用try...catch块。try块包含可能抛出异常的代码，而catch块用于捕获并处理这些异常。
try { // 可能抛出异常的代码 } catch (const std::exception&amp; e) { // 处理异常 std::cerr &lt;&lt; &#34;捕获到异常: &#34; &lt;&lt; e.what() &lt;&lt; std::endl; } 一个try后面可以跟着多个catch，因为一段代码可能出现多种异常
try { // 保护的标识代码 }catch( ExceptionName e1 ) { // catch 块 }catch( ExceptionName e2 ) { // catch 块 }catch( ExceptionName eN ) { // catch 块 } 2.">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-08-08T22:06:05+08:00">
    <meta property="article:modified_time" content="2024-08-08T22:06:05+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">【C&#43;&#43;进阶学习】第十二弹——C&#43;&#43; 异常处理：深入解析与实践应用</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p><strong>前言：</strong></p> 
<blockquote> 
 <p>在C++编程语言中，异常处理是一种重要的机制，它允许程序员在运行时捕获和处理错误或异常情况。本文将详细介绍C++异常处理的相关知识点，包括异常的定义、抛出与捕获、异常处理的原则、以及在实际编程中的应用。</p> 
</blockquote> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="-toc" style="margin-left:80px;"></p> 
<p id="1.%20%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5-toc" style="margin-left:80px;"><a href="#1.%20%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5" rel="nofollow">1. 异常处理的基本概念</a></p> 
<p id="1.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89-toc" style="margin-left:120px;"><a href="#1.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89" rel="nofollow">1.1 异常的定义</a></p> 
<p id="1.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA-toc" style="margin-left:120px;"><a href="#1.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA" rel="nofollow">1.2 异常的抛出</a></p> 
<p id="1.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7-toc" style="margin-left:120px;"><a href="#1.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7" rel="nofollow">1.3 异常的捕获</a></p> 
<p id="2.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8-toc" style="margin-left:40px;"><a href="#2.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8" rel="nofollow">2. 异常的使用</a></p> 
<p id="2.1%20%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E7%9A%84%E5%8E%9F%E5%88%99-toc" style="margin-left:120px;"><a href="#2.1%20%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E7%9A%84%E5%8E%9F%E5%88%99" rel="nofollow">2.1 异常抛出和匹配的原则</a></p> 
<p id="2.2%20%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E7%9A%84%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99-toc" style="margin-left:120px;"><a href="#2.2%20%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E7%9A%84%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99" rel="nofollow">2.2 在函数调用链中异常栈的展开匹配原则</a></p> 
<p id="3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA-toc" style="margin-left:80px;"><a href="#3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA" rel="nofollow">3. 异常的重新抛出</a></p> 
<p id="4.%20%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8-toc" style="margin-left:80px;"><a href="#4.%20%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8" rel="nofollow">4. 异常安全</a></p> 
<p id="5.%20%E5%BC%82%E5%B8%B8%E8%A7%84%E6%A0%BC-toc" style="margin-left:80px;"><a href="#5.%20%E5%BC%82%E5%B8%B8%E8%A7%84%E6%A0%BC" rel="nofollow">5. 异常规格</a></p> 
<p id="6.%C2%A0C%2B%2B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%AE%9E%E8%B7%B5%E5%BA%94%E7%94%A8-toc" style="margin-left:80px;"><a href="#6.%C2%A0C%2B%2B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%AE%9E%E8%B7%B5%E5%BA%94%E7%94%A8" rel="nofollow">6. C++异常处理的实践应用</a></p> 
<p id="6.1%20%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C%E5%BC%82%E5%B8%B8-toc" style="margin-left:120px;"><a href="#6.1%20%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C%E5%BC%82%E5%B8%B8" rel="nofollow">6.1 文件操作异常</a></p> 
<p id="6.2%20%E6%95%B0%E5%AD%A6%E8%BF%90%E7%AE%97%E5%BC%82%E5%B8%B8-toc" style="margin-left:120px;"><a href="#6.2%20%E6%95%B0%E5%AD%A6%E8%BF%90%E7%AE%97%E5%BC%82%E5%B8%B8" rel="nofollow">6.2 数学运算异常</a></p> 
<p id="7.%20%E6%80%BB%E7%BB%93-toc" style="margin-left:80px;"><a href="#7.%20%E6%80%BB%E7%BB%93" rel="nofollow">7. 总结</a></p> 
<hr id="hr-toc"> 
<p></p> 
<h4 id="1.%20%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5">1. 异常处理的基本概念</h4> 
<blockquote> 
 <p>在C++中，异常处理是一种机制，用于处理运行时发生的错误或异常情况。异常可以是程序执行过程中遇到的任何问题，如除以零、文件读写错误、资源未正确释放等。</p> 
</blockquote> 
<h5 id="1.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89">1.1 异常的定义</h5> 
<blockquote> 
 <p>在C++中，异常是一个对象，通常由<strong><code><span style="background-color:#ffd900;">std::exception</span></code></strong>或其派生类创建。异常对象包含了错误信息和状态，程序员可以使用这些信息来诊断和处理错误。</p> 
</blockquote> 
<h5 id="1.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA">1.2 异常的抛出</h5> 
<blockquote> 
 <p>异常的抛出使用<strong><code><span style="background-color:#ffd900;">throw</span></code></strong>关键字。程序员在代码中使用<strong><code><span style="background-color:#ffd900;">throw</span></code></strong>语句来抛出异常，这可以是显式抛出一个异常对象，也可以是抛出一个特定类型的异常（如<strong><code><span style="background-color:#ffd900;">std::runtime_error</span></code></strong>）。</p> 
</blockquote> 
<pre><code class="language-cpp">throw std::runtime_error("发生了一个错误");</code></pre> 
<h5 id="1.3%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7">1.3 异常的捕获</h5> 
<blockquote> 
 <p>异常的捕获使用<span style="color:#0d0016;"><strong><code><span style="background-color:#ffd900;">try...catch</span></code></strong></span>块。<strong><code><span style="background-color:#ffd900;">try</span></code></strong>块包含可能抛出异常的代码，而<strong><code><span style="background-color:#ffd900;">catch</span></code></strong>块用于捕获并处理这些异常。</p> 
</blockquote> 
<pre><code class="language-cpp">try {
    // 可能抛出异常的代码
} catch (const std::exception&amp; e) {
    // 处理异常
    std::cerr &lt;&lt; "捕获到异常: " &lt;&lt; e.what() &lt;&lt; std::endl;
}</code></pre> 
<blockquote> 
 <p>一个try后面可以跟着多个catch，因为一段代码可能出现多种异常</p> 
</blockquote> 
<pre><code class="language-cpp">try
{
  // 保护的标识代码
}catch( ExceptionName e1 )
{
  // catch 块
}catch( ExceptionName e2 )
{
  // catch 块
}catch( ExceptionName eN )
{
  // catch 块
}</code></pre> 
<h3 id="2.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8">2. 异常的使用</h3> 
<h5 id="2.1%20%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BA%E5%92%8C%E5%8C%B9%E9%85%8D%E7%9A%84%E5%8E%9F%E5%88%99">2.1 异常抛出和匹配的原则</h5> 
<p><strong><span style="background-color:#ffd900;">1. 异常是通过抛出对象来激活的，该对象的类型决定了应该激活那个catch的处理代码</span></strong></p> 
<p><strong><span style="background-color:#ffd900;">2. 如果有多个处理代码与对象类型匹配，那么就激活离的最近的一个</span></strong></p> 
<p><img alt="" height="682" src="https://images2.imgbox.com/1b/35/P2cyjakO_o.png" width="1200"></p> 
<p><span style="color:#0d0016;"><strong><span style="background-color:#ffd900;">3. 抛出异常对象时，会生成一个临时对象的拷贝，这个临时对象的拷贝会在被catch以后销毁</span></strong></span></p> 
<p><img alt="" height="671" src="https://images2.imgbox.com/95/71/mpqQ2Udb_o.png" width="895"></p> 
<p>4. 异常的捕获所有原则：</p> 
<blockquote> 
 <ul><li>可以使用 <strong><code><span style="background-color:#ffd900;">catch(...)</span></code></strong> 来捕获所有类型的异常。这种捕获方式通常用于那些不关心异常具体类型，只想处理所有异常的情况。</li></ul> 
</blockquote> 
<h5 id="2.2%20%E5%9C%A8%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E9%93%BE%E4%B8%AD%E5%BC%82%E5%B8%B8%E6%A0%88%E7%9A%84%E5%B1%95%E5%BC%80%E5%8C%B9%E9%85%8D%E5%8E%9F%E5%88%99">2.2 在函数调用链中异常栈的展开匹配原则</h5> 
<blockquote> 
 <p>1. 首先检查throw本身是否在try块内部，如果是再查找是否有匹配的catch，如果有，则直接调用</p> 
 <p>2. 如果所在函数栈没有匹配的catch，则退出当前函数栈，到调用该函数的栈中进行寻找</p> 
 <p>3. 如果找到main函数的栈中，依然没有匹配的catch，则会直接终止程序。为了防止终止程序的这种情况出现，我们一般都会在main函数中加入一个catch(...)捕获任意类型的异常</p> 
 <div>
   4. 找到匹配的catch后 ，就会继续执行catch中的语句 
 </div> 
</blockquote> 
<div> 
 <img alt="" height="725" src="https://images2.imgbox.com/81/a5/do0217fd_o.png" width="1200"> 
</div> 
<div></div> 
<div> 
 <pre><code class="language-cpp">#include&lt;iostream&gt;
using namespace std;
double func2(int x, int y)
{
	if (x == 0)
		throw "除0错误";
	else
		return (double)x / (double)y;
}
void func1()
{
	int x, y;
	cin &gt;&gt; x &gt;&gt; y;
	cout &lt;&lt; func2(x, y) &lt;&lt; endl;
}
int main()
{
	try{
		func1();
	}
	catch (const int e){
		cout &lt;&lt; e &lt;&lt; endl;
	}
	catch (const char* e){
		cout &lt;&lt; e &lt;&lt; endl;
	}
	catch (...) {
		cout &lt;&lt; "未知异常" &lt;&lt; endl;
	}
	return 0;
}</code></pre> 
 <h4 id="3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA">3. 异常的重新抛出</h4> 
 <ul><li>在 <strong><code><span style="background-color:#ffd900;">catch</span></code><span style="background-color:#ffd900;"> </span></strong>块中，可以使用<strong><span style="background-color:#ffd900;"> </span><code><span style="background-color:#ffd900;">throw</span></code><span style="background-color:#ffd900;">（不带参数）</span><code><span style="background-color:#ffd900;">;</span></code></strong>来重新抛出当前捕获的异常。这通常用于在处理完一些资源清理工作后，将异常传递给更高层的调用者。</li></ul> 
 <pre><code class="language-cpp">
void func1()
{
	// 这里可以看到如果发生除0错误抛出异常，另外下面的array没有得到释放。
    // 所以这里捕获异常后并不处理异常，异常还是交给外面处理，这里捕获了再
    // 重新抛出去。
	int* arr = new int[10];
	try{
		int x, y;
		cin &gt;&gt; x &gt;&gt; y;
		cout &lt;&lt; func2(x, y) &lt;&lt; endl;
	}
	catch(...){
		delete arr;
		throw;
	}
}
</code></pre> 
 <h4 id="4.%20%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8">4. 异常安全</h4> 
 <blockquote> 
  <ul><li>在构造函数和析构函数中应避免抛出异常，因为这可能导致对象状态不一致或资源泄漏。</li><li>应该使用 RAII（Resource Acquisition Is Initialization）原则来管理资源，确保异常发生时资源能够自动释放。（这个会在后面讲智能指针时讲到）</li></ul> 
 </blockquote> 
 <h4 id="5.%20%E5%BC%82%E5%B8%B8%E8%A7%84%E6%A0%BC">5. 异常规格</h4> 
 <blockquote> 
  <ul><li>可以在函数声明中使用异常规格来指定函数可能抛出的异常类型。这有助于调用者了解预期的异常，并做出相应的处理。</li></ul> 
 </blockquote> 
 <p>下面是几种常见的异常规格：</p> 
 <pre><code class="language-cpp">// 这里表示这个函数会抛出A/B/C/D中的某种类型的异常
void fun() throw(A，B，C，D);
// 这里表示这个函数只会抛出bad_alloc的异常
void* operator new (std::size_t size) throw (std::bad_alloc);
// 这里表示这个函数不会抛出异常
void* operator delete (std::size_t size, void* ptr) throw();
// C++11 中新增的noexcept，表示不会抛异常
thread() noexcept;
thread (thread&amp;&amp; x) noexcept;</code></pre> 
 <h4 id="6.%C2%A0C%2B%2B%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E7%9A%84%E5%AE%9E%E8%B7%B5%E5%BA%94%E7%94%A8">6. C++异常处理的实践应用</h4> 
 <h5 id="6.1%20%E6%96%87%E4%BB%B6%E6%93%8D%E4%BD%9C%E5%BC%82%E5%B8%B8">6.1 文件操作异常</h5> 
 <blockquote> 
  <p>在进行文件操作时，可以使用异常处理来捕获和处理可能发生的错误，如文件不存在、权限问题等。<code> </code></p> 
 </blockquote> 
 <pre><code class="language-cpp">#include &lt;fstream&gt;
#include &lt;iostream&gt;

void readFile(const std::string&amp; filename) {
    std::ifstream file(filename);
    if (!file) {
        throw std::runtime_error("无法打开文件");
    }
    // 读取文件内容
}

int main() {
    try {
        readFile("example.txt");
    } catch (const std::exception&amp; e) {
        std::cerr &lt;&lt; "错误: " &lt;&lt; e.what() &lt;&lt; std::endl;
    }
    return 0;
}</code></pre> 
 <h5 id="6.2%20%E6%95%B0%E5%AD%A6%E8%BF%90%E7%AE%97%E5%BC%82%E5%B8%B8">6.2 数学运算异常</h5> 
 <blockquote> 
  <p>在进行数学运算时，可以捕获除以零等异常情况。（上面的例子中也是这种）</p> 
 </blockquote> 
 <pre><code class="language-cpp">#include &lt;iostream&gt;
#include &lt;stdexcept&gt;

void safeDivide(double a, double b) {
    if (b == 0) {
        throw std::runtime_error("除数不能为零");
    }
    std::cout &lt;&lt; "结果: " &lt;&lt; a / b &lt;&lt; std::endl;
}

int main() {
    try {
        safeDivide(10, 0);
    } catch (const std::exception&amp; e) {
        std::cerr &lt;&lt; "错误: " &lt;&lt; e.what() &lt;&lt; std::endl;
    }
    return 0;
}</code></pre> 
 <h4 id="7.%20%E6%80%BB%E7%BB%93">7. 总结</h4> 
 <blockquote> 
  <p>异常能够帮助我们快速找到错误并判断错误类型，增强我们处理错误的能力，但同时异常也会带来执行流跳跃，给我们调试等带来一些难题，但总的来说，异常还是给我们工作带来极大的便利，如何正确使用异常，是我们玩转C++的重要一步。</p> 
 </blockquote> 
 <p style="text-align:center;"><img alt="" src="https://images2.imgbox.com/a0/90/FVasAdLN_o.jpg"></p> 
 <p><strong><span style="background-color:#ffd900;">感谢各位大佬观看，创作不易，还请各位大佬点赞支持！！！</span></strong></p> 
 <p></p> 
</div>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/2e6d2927619dbd003b2a49669b831f4c/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">[python]如何正确的安装pytorch?(详细)</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/b4bc7188f7d066f350e1d01a252b9bb3/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">vue.config.js 配置configureWebpack 和 chainWebpack 以及一些常用配置</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>