<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Java 异常处理详解（如果想知道Java中有关异常处理的知识点，那么只看这一篇就足够了！） - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/2f886db77222c2c222cc00eef3a59af6/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="Java 异常处理详解（如果想知道Java中有关异常处理的知识点，那么只看这一篇就足够了！）">
  <meta property="og:description" content="前言：异常处理是 Java 编程中非常重要的一部分，它能够有效地捕获和处理程序运行中的错误，提高代码的健壮性和可靠性。本文将深入探讨 Java 中异常的概念、体系结构、抛出、解决方式以及如何自定义异常，并结合代码案例进行详细解释。
✨✨✨这里是秋刀鱼不做梦的BLOG
✨✨✨想要了解更多内容可以访问我的主页秋刀鱼不做梦-CSDN博客
先让我们看一下本文的大致内容：
目录
1.异常的概念
1. NullPointerException（空指针异常）
2. ArrayIndexOutOfBoundsException（数组越界异常）
3. ArithmeticException（算术异常）
2.异常的体系结构
（1）异常的体系结构
（2）异常的分类
1.编译时异常：
2.运行时异常：
3.异常的抛出
4.异常的解决方式
（1）异常声明throws
（2）使用try - catch - finally语句
补充：异常处理流程总结
5.自定义异常
1.异常的概念 ——在学习Java中的异常之前，先让我们了解一下什么是Java中的异常：
在 Java 中，异常（Exception）是指程序在执行过程中遇到的不正常情况，这些情况可能导致程序无法继续执行或产生错误的结果。异常可以是 Java 标准库中提供的内置异常类，也可以是开发人员自定义的异常类。
相信读者在日常的编写代码的时候，或多或少的都遇到过一些异常，只是读者你可能没有太注意它们，比如如下异常：
1. NullPointerException（空指针异常） 空指针异常通常发生在尝试访问对象的属性或调用对象的方法时，而该对象为 null 的情况下。
public class NullPointerExceptionExample { public static void main(String[] args) { String str = null; System.out.println(str.length()); // 这行代码会抛出 NullPointerException } } 2. ArrayIndexOutOfBoundsException（数组越界异常） 数组越界异常发生在尝试访问数组的不存在的索引位置时。
public class ArrayIndexOutOfBoundsExceptionExample { public static void main(String[] args) { int[] arr = new int[3]; System.">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-06-03T14:31:06+08:00">
    <meta property="article:modified_time" content="2024-06-03T14:31:06+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Java 异常处理详解（如果想知道Java中有关异常处理的知识点，那么只看这一篇就足够了！）</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p> <strong>       前言：异常处理是 Java 编程中非常重要的一部分，它能够有效地捕获和处理程序运行中的错误，提高代码的健壮性和可靠性。本文将深入探讨 Java 中异常的概念、体系结构、抛出、解决方式以及如何自定义异常，并结合代码案例进行详细解释。</strong></p> 
<hr> 
<blockquote> 
 <p style="text-align:center;"><img alt="" src="https://images2.imgbox.com/f1/15/nygECFto_o.jpg"></p> 
 <p><strong>✨✨<span style="color:#ff9900;">✨这里是秋刀鱼不做梦的BLOG</span></strong></p> 
 <p><span style="color:#ff9900;"><strong>✨✨✨想要了解更多内容可以访问我的主页</strong></span><a href="https://blog.csdn.net/2302_80198073?type=blog" title="秋刀鱼不做梦-CSDN博客">秋刀鱼不做梦-CSDN博客</a></p> 
</blockquote> 
<p><span style="color:#a2e043;"><strong>先让我们看一下本文的大致内容：</strong></span></p> 
<p style="text-align:center;"><span style="color:#a2e043;"><strong><img alt="" src="https://images2.imgbox.com/6c/cc/mj75VxBc_o.png"></strong></span></p> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="1.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5-toc" style="margin-left:0px;"><strong><a href="#1.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5" rel="nofollow">1.异常的概念</a></strong></p> 
<p id="1.%20NullPointerException%EF%BC%88%E7%A9%BA%E6%8C%87%E9%92%88%E5%BC%82%E5%B8%B8%EF%BC%89-toc" style="margin-left:40px;"><strong><a href="#1.%20NullPointerException%EF%BC%88%E7%A9%BA%E6%8C%87%E9%92%88%E5%BC%82%E5%B8%B8%EF%BC%89" rel="nofollow">1. NullPointerException（空指针异常）</a></strong></p> 
<p id="2.%20ArrayIndexOutOfBoundsException%EF%BC%88%E6%95%B0%E7%BB%84%E8%B6%8A%E7%95%8C%E5%BC%82%E5%B8%B8%EF%BC%89-toc" style="margin-left:40px;"><strong><a href="#2.%20ArrayIndexOutOfBoundsException%EF%BC%88%E6%95%B0%E7%BB%84%E8%B6%8A%E7%95%8C%E5%BC%82%E5%B8%B8%EF%BC%89" rel="nofollow">2. ArrayIndexOutOfBoundsException（数组越界异常）</a></strong></p> 
<p id="3.%20ArithmeticException%EF%BC%88%E7%AE%97%E6%9C%AF%E5%BC%82%E5%B8%B8%EF%BC%89-toc" style="margin-left:40px;"><strong><a href="#3.%20ArithmeticException%EF%BC%88%E7%AE%97%E6%9C%AF%E5%BC%82%E5%B8%B8%EF%BC%89" rel="nofollow">3. ArithmeticException（算术异常）</a></strong></p> 
<p id="2.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84-toc" style="margin-left:0px;"><strong><a href="#2.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84" rel="nofollow">2.异常的体系结构</a></strong></p> 
<p id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84-toc" style="margin-left:40px;"><strong><a href="#%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84" rel="nofollow">        （1）异常的体系结构</a></strong></p> 
<p id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB-toc" style="margin-left:40px;"><strong><a href="#%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB" rel="nofollow">        （2）异常的分类</a></strong></p> 
<p id="1.%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A-toc" style="margin-left:80px;"><strong><a href="#1.%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A" rel="nofollow">1.编译时异常：</a></strong></p> 
<p id="2.%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A-toc" style="margin-left:80px;"><strong><a href="#2.%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A" rel="nofollow">2.运行时异常：</a></strong></p> 
<p id="3.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA-toc" style="margin-left:0px;"><strong><a href="#3.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA" rel="nofollow">3.异常的抛出</a></strong></p> 
<p id="4.%E5%BC%82%E5%B8%B8%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E5%BC%8F-toc" style="margin-left:0px;"><strong><a href="#4.%E5%BC%82%E5%B8%B8%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E5%BC%8F" rel="nofollow">4.异常的解决方式</a></strong></p> 
<p id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows-toc" style="margin-left:40px;"><strong><a href="#%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows" rel="nofollow">        （1）异常声明throws</a></strong></p> 
<p id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E4%BD%BF%E7%94%A8try%20-%20catch%20-%20finally%E8%AF%AD%E5%8F%A5-toc" style="margin-left:40px;"><strong><a href="#%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E4%BD%BF%E7%94%A8try%20-%20catch%20-%20finally%E8%AF%AD%E5%8F%A5" rel="nofollow">        （2）使用try - catch - finally语句</a></strong></p> 
<p id="%E8%A1%A5%E5%85%85%EF%BC%9A%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B%E6%80%BB%E7%BB%93-toc" style="margin-left:40px;"><strong><a href="#%E8%A1%A5%E5%85%85%EF%BC%9A%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B%E6%80%BB%E7%BB%93" rel="nofollow">补充：异常处理流程总结</a></strong></p> 
<p id="5.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8-toc" style="margin-left:0px;"><strong><a href="#5.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8" rel="nofollow">5.自定义异常</a></strong></p> 
<hr id="hr-toc"> 
<p></p> 
<h2 id="1.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5"><span style="color:#956fe7;">1.异常的概念</span></h2> 
<p>    <strong>    ——在学习Java中的异常之前，先让我们了解一下什么是Java中的异常：</strong></p> 
<blockquote> 
 <p><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>在 Java 中，异常（Exception）是指程序在执行过程中遇到的不正常情况，这些情况可能导致程序无法继续执行或产生错误的结果。异常可以是 Java 标准库中提供的内置异常类，也可以是开发人员自定义的异常类。</strong></span></p> 
</blockquote> 
<p>        相信读者在日常的编写代码的时候，或多或少的都遇到过一些异常，只是读者你可能没有太注意它们，比如如下异常：</p> 
<h3 id="1.%20NullPointerException%EF%BC%88%E7%A9%BA%E6%8C%87%E9%92%88%E5%BC%82%E5%B8%B8%EF%BC%89"><span style="color:#4da8ee;">1. NullPointerException（空指针异常）</span></h3> 
<p><strong><span style="color:#ffd900;">空指针异常通常发生在尝试访问对象的属性或调用对象的方法时，而该对象为 null 的情况下。</span></strong></p> 
<pre><code class="language-java">public class NullPointerExceptionExample {
    public static void main(String[] args) {
        String str = null;
        System.out.println(str.length()); // 这行代码会抛出 NullPointerException
    }
}
</code></pre> 
<p></p> 
<h3 id="2.%20ArrayIndexOutOfBoundsException%EF%BC%88%E6%95%B0%E7%BB%84%E8%B6%8A%E7%95%8C%E5%BC%82%E5%B8%B8%EF%BC%89"><span style="color:#4da8ee;">2. ArrayIndexOutOfBoundsException（数组越界异常）</span></h3> 
<p><span style="color:#ffd900;"><strong>数组越界异常发生在尝试访问数组的不存在的索引位置时。</strong></span></p> 
<pre><code class="language-java">public class ArrayIndexOutOfBoundsExceptionExample {
    public static void main(String[] args) {
        int[] arr = new int[3];
        System.out.println(arr[5]); // 这行代码会抛出 ArrayIndexOutOfBoundsException
    }
}
</code></pre> 
<p></p> 
<h3 id="3.%20ArithmeticException%EF%BC%88%E7%AE%97%E6%9C%AF%E5%BC%82%E5%B8%B8%EF%BC%89"><span style="color:#4da8ee;">3. ArithmeticException（算术异常）</span></h3> 
<p><span style="color:#ffd900;"><strong>算术异常发生在进行除以零的算术运算时。</strong></span></p> 
<pre><code class="language-java">public class ArithmeticExceptionExample {
    public static void main(String[] args) {
        int a = 10;
        int b = 0;
        System.out.println(a / b); // 这行代码会抛出 ArithmeticException
    }
}
</code></pre> 
<p>        当然，这以上只是举出来几个常见的异常的案例，所以我们就可以知道了异常类型和如何处理它们对于编写健壮的 Java 代码非常重要。</p> 
<p></p> 
<p></p> 
<h2 id="2.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84"><span style="color:#956fe7;">2.异常的体系结构</span></h2> 
<h3 id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0"><span style="color:#ffd900;">        </span></h3> 
<h3 id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84"><span style="color:#ffd900;">        </span><span style="color:#ffd900;">（1）异常的体系结构</span></h3> 
<p>      <span style="color:#38d8f0;"><strong>  在Java中，Java 异常体系结构是由一组类构成的，它们都是 <code>Throwable</code> 类的子类。常见的异常类包括 <code>Error</code>、<code>RuntimeException</code> 以及它们的子类。<code>Error</code> 类及其子类通常表示严重的错误，如系统错误或虚拟机错误，程序通常无法恢复。<code>RuntimeException</code> 及其子类通常表示程序逻辑错误或运行时错误，如空指针异常、数组越界异常等。</strong></span></p> 
<p><strong>我们可以直接看一下以下这幅图进行理解：</strong></p> 
<p><strong><img alt="" src="https://images2.imgbox.com/bd/b5/ugzF5RRa_o.png"></strong></p> 
<p><strong>从上图中可以看到：</strong></p> 
<blockquote> 
 <p><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>1. Throwable：是异常体系的顶层类，其派生出两个重要的子类, Error 和 Exception；</strong></span><br><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>2. Error：指的是Java虚拟机无法解决的严重问题，比如：JVM的内部错误、资源耗尽等，典型代表：StackOverflowError和OutOfMemoryError，一旦发生回力乏术；</strong></span><br><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>3. Exception：异常产生后程序员可以通过代码进行处理，使程序继续执行。比如：感冒、发烧。我们平时所说的异常就是Exception；</strong></span></p> 
</blockquote> 
<h3><span style="color:#ffd900;">        </span></h3> 
<h3 id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB"><span style="color:#ffd900;">        </span><span style="color:#ffd900;">（2）异常的分类</span></h3> 
<p>    <span style="color:#38d8f0;">   <strong> 在Java中，异常可能在编译时发生，也可能在程序运行时发生，根据发生的时机不同，可以将异常分为两类：</strong></span></p> 
<h4 id="1.%E7%BC%96%E8%AF%91%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A"><span style="color:#fe2c24;"><strong>1.编译时异常</strong>：</span></h4> 
<blockquote> 
 <p>      <span style="color:#ff9900;"><strong>  这是因为程序员必须处理这种异常，否则编译器会报错。在Java中最典型的编译时异常为<code>FileNotFoundException</code>，它会在尝试打开不存在的文件时抛出。</strong></span></p> 
</blockquote> 
<pre><code class="language-java">import java.io.File;
import java.io.FileReader;
import java.io.FileNotFoundException;

public class CompileTimeExceptionExample {
    public static void main(String[] args) {
        try {
            File file = new File("nonexistent_file.txt"); // 这里假设文件不存在
            FileReader fr = new FileReader(file); // 可能抛出 FileNotFoundException
        } catch (FileNotFoundException e) {
            System.out.println("文件未找到异常：" + e.getMessage());
        }
    }
}
</code></pre> 
<p><span style="color:#fe2c24;"><strong>注意：</strong></span></p> 
<blockquote> 
 <p><span style="color:#fe2c24;"><strong>        编译时出现的语法性错误，不能称之为异常。例如将 System.out.println 拼写错了, 写成了system.out.println. 此时编译过程中就会出错, 这是 "编译期" 出错。而运行时指的是程序已经编译通过得到class 文件了, 再由 JVM 执行过程中出现的错误.</strong></span></p> 
</blockquote> 
<h4></h4> 
<h4 id="2.%E8%BF%90%E8%A1%8C%E6%97%B6%E5%BC%82%E5%B8%B8%EF%BC%9A"><span style="color:#fe2c24;">2.运行时异常：</span></h4> 
<blockquote> 
 <p>        <span style="color:#ff9900;"><strong>这些异常不需要强制捕获或处理，因为它们通常是由程序逻辑错误引起的。一个常见的运行时异常是 <code>ArrayIndexOutOfBoundsException</code>，当尝试访问数组中不存在的索引时会抛出。</strong></span></p> 
</blockquote> 
<pre><code class="language-java">public class RunTimeExceptionExample {
    public static void main(String[] args) {
        int[] array = {1, 2, 3};
        try {
            System.out.println(array[5]); // 可能抛出 ArrayIndexOutOfBoundsException
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("数组越界异常：" + e.getMessage());
        }
    }
}
</code></pre> 
<p><strong>这样我们就大致的了解了异常的体系结构了。</strong></p> 
<p></p> 
<p></p> 
<h2 id="3.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA"><span style="color:#956fe7;"><strong>3.</strong>异常的抛出</span></h2> 
<p>       <strong> 当然，在编写程序时，如果程序中出现错误，此时就需要将错误的信息告知给调用者，比如：参数检测。在Java中，可以借助throw关键字，抛出一个指定的异常对象，将错误信息告知给调用者。具体语法如下：</strong></p> 
<pre><code class="language-java">throw new XXXException("异常产生的原因");</code></pre> 
<p><span style="color:#ffd900;"><strong>让我们看一下一个案例：</strong></span></p> 
<pre><code class="language-java">public static void validateAge(int age) {
        if (age &lt; 18) {
            //异常的抛出
            throw new InvalidAgeException("未满18岁，不允许访问。");
        }
        System.out.println("年龄验证通过。");
}</code></pre> 
<p><span style="color:#fe2c24;"><strong>【注意事项】</strong></span></p> 
<blockquote> 
 <p><span style="color:#ff9900;"><strong>1. throw必须写在方法体内部<br> 2. 抛出的对象必须是Exception 或者 Exception 的子类对象<br> 3. 如果抛出的是 RunTimeException 或者 RunTimeException 的子类，则可以不用处理，直接交给JVM来处理<br> 4. 如果抛出的是编译时异常，用户必须处理，否则无法通过编译<br> 5. 异常一旦抛出，其后的代码就不会执行</strong></span></p> 
</blockquote> 
<p>         <strong>这样我们就大致的了解了如果有异常之后，我们如果将其进行抛出了。但是异常是抛出了，那我们如何去解决抛出的异常呢？</strong></p> 
<p></p> 
<p></p> 
<h2 id="4.%E5%BC%82%E5%B8%B8%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E5%BC%8F"><span style="color:#956fe7;">4.异常的解决方式</span></h2> 
<p><span style="color:#a2e043;"><strong>        </strong></span><span style="color:#a2e043;"><strong>——在Java中异常的具体处理方式主要有两种：异常声明 throws 以及 try-catch捕获处理。</strong></span></p> 
<h3 id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%881%EF%BC%89%E5%BC%82%E5%B8%B8%E5%A3%B0%E6%98%8Ethrows"><span style="color:#4da8ee;">        </span><span style="color:#4da8ee;">（1）异常声明throws</span></h3> 
<p>      <strong>  当方法中抛出编译时异常，用户不想处理该异常，此时就可以借助throws将异常抛给方法的调用者来处理。即当前方法不处理异常，提醒方法的调用者处理异常。</strong></p> 
<p><span style="color:#ff9900;"><strong>其语法形式为：</strong></span></p> 
<pre><code class="language-java">修饰符 返回值类型 方法名(参数列表) throws 异常类型1，异常类型2...{


}</code></pre> 
<p><span style="color:#ffd900;"><strong>让我们直接使用一个案例来进一步帮助你进行理解：</strong></span></p> 
<pre><code class="language-java">public static void divide(int a, int b) throws ArithmeticException {
        if (b == 0) {
            throw new ArithmeticException("除数不能为0");
        }
        int result = a / b;
        System.out.println("结果：" + result);
}</code></pre> 
<p><span style="color:#38d8f0;"><strong>        </strong></span><span style="color:#38d8f0;"><strong>我们可以在这个案例中看到，如果b == 0时，我们抛出了异常，但是我们并没有在此方法中对该异常进行处理，而是将其继续抛出，给调用者处理。这就是第一种处理异常的方</strong><strong>式</strong><strong>throws。</strong></span></p> 
<p><span style="color:#fe2c24;">【注意事项】</span></p> 
<blockquote> 
 <p><span style="color:#fe2c24;"><strong>1. throws必须跟在方法的参数列表之后<br> 2. 声明的异常必须是 Exception 或者 Exception 的子类<br> 3. 方法内部如果抛出了多个异常，throws之后必须跟多个异常类型，之间用逗号隔开，如果抛出多个异常类型具有父子关系，直接声明父类即可。</strong></span></p> 
 <p><span style="color:#fe2c24;"><strong>4. 调用声明抛出异常的方法时，调用者必须对该异常进行处理，或者继续使用throws抛出</strong></span></p> 
</blockquote> 
<p></p> 
<h3 id="%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%EF%BC%882%EF%BC%89%E4%BD%BF%E7%94%A8try%20-%20catch%20-%20finally%E8%AF%AD%E5%8F%A5"><span style="color:#4da8ee;"><strong>        </strong></span><span style="color:#4da8ee;"><strong>（2）使用try - catch - finally语句</strong></span></h3> 
<p><strong>        ——在Java中，异常可以通过try-catch-finally语句块来进行处理。由于throws对异常并没有真正处理，而是将异常报告给抛出异常方法的调用者，由调用者处理。如果真正要对异常进行处理，就需要try-catch。</strong></p> 
<p><span style="color:#ffd900;"><strong>其基本语法为：</strong></span></p> 
<pre><code class="language-java">try {
    // 可能抛出异常的代码
} catch (ExceptionType1 e1) {
    // 处理异常类型1的情况
} catch (ExceptionType2 e2) {
    // 处理异常类型2的情况
} finally {
    // 可选的finally语句块，用于执行清理操作
}
</code></pre> 
<p>      <strong>  在try语句块中，我们可以放置可能抛出异常的代码。如果try语句块中的代码抛出了异常，那么异常会被catch语句块捕获。catch语句块中的参数指定了要捕获的异常类型，当抛出的异常与catch语句块中指定的类型匹配时，相应的catch语句块会被执行。如果try语句块中的代码未抛出异常，则catch语句块会被跳过。</strong></p> 
<p><strong>        另外，finally语句块是可选的，用于执行清理操作，无论是否发生异常都会执行。finally语句块通常用于释放资源或执行必要的收尾工作，例如关闭文件或数据库连接。</strong></p> 
<p></p> 
<p><span style="color:#ff9900;"><strong>这里我们使用一个案例来帮助你进一步理解：</strong></span></p> 
<pre><code class="language-java">public class SimpleExceptionHandlingExample {

    public static void main(String[] args) {
        int a = 10;
        int b = 0;
        int result = 0;
        try {
            // 尝试进行除法运算
            result = a / b;
            System.out.println("除法运算结果：" + result);
        } catch (ArithmeticException e) {
            // 捕获除零异常并输出错误信息
            System.err.println("除法运算出错：除数不能为零");
        } finally {
            // 无论是否发生异常，都会执行的代码块
            System.out.println("finally块：结束异常处理");
        }
    }
}
</code></pre> 
<p>     <span style="color:#38d8f0;"><strong>   首先我们对10除以0进行除法运算。由于除数为0，会抛出ArithmeticException异常。我们在try块中捕获这个异常，并输出错误信息。无论是否发生异常，finally块中的代码都会执行，这里我们简单输出一条结束异常处理的消息。</strong></span></p> 
<p><strong><span style="color:#fe2c24;">【注意事项】</span></strong></p> 
<blockquote> 
 <p><span style="color:#fe2c24;"><strong>1. try块内抛出异常位置之后的代码将不会被执行<br> 2. 如果抛出异常类型与catch时异常类型不匹配，即异常不会被成功捕获，也就不会被处理，继续往外抛，直到JVM收到后中断程序----异常是按照类型来捕获的</strong></span></p> 
 <p><span style="color:#fe2c24;"><strong>3. try中可能会抛出多个不同的异常对象，则必须用多个catch来捕获----即多种异常，多次捕获</strong></span></p> 
 <p><span style="color:#fe2c24;"><strong>4. 如果多个异常的处理方式是完全相同，我们可以使用“ | ”隔开</strong></span></p> 
 <p><span style="color:#fe2c24;"><strong>5. 如果异常之间具有父子关系，一定是子类异常在前catch，父类异常在后catch，否则语法错误</strong></span></p> 
</blockquote> 
<p><strong>这里我们对第四条加以解释：</strong><span style="color:#ffd900;"><strong>如果多个异常的处理方式是完全相同，我们可以使用“ | ”隔开</strong></span></p> 
<p>例如：</p> 
<pre><code class="language-java">catch (ArrayIndexOutOfBoundsException | NullPointerException e) {
    //对异常进行处理的代码
}</code></pre> 
<p><strong>     <span style="color:#38d8f0;">   </span>——当然我们可以一直 | 添加异常，但是实际上不建议使用这样的方式处理，因为这样处理我们将不知道到底try中代码出现了什么类型的异常     （<span style="color:#a2e043;">比如上面的代码可能出现的异常类型为ArrayIndexOutOfBoundsException ，也可能是 NullPointerException异常类型</span>）</strong></p> 
<p><strong>这样我们就大致的了解了Java处理异常的两种方式了。</strong></p> 
<p></p> 
<h3 id="%E8%A1%A5%E5%85%85%EF%BC%9A%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B%E6%80%BB%E7%BB%93"><span style="color:#ff9900;"><strong>补充：异常处理流程总结</strong></span></h3> 
<blockquote> 
 <p><strong>        1. 程序先执行 try 中的代码.<br>         2. 如果 try 中的代码出现异常, 就会结束 try 中的代码, 看和 catch 中的异常类型是否匹配.<br>         3. 如果找到匹配的异常类型, 就会执行 catch 中的代码.<br>         4. 如果没有找到匹配的异常类型, 就会将异常向上传递到上层调用者.<br>         5. 无论是否找到匹配的异常类型, finally 中的代码都会被执行到(在该方法结束之前执行).<br>         6. 如果上层调用者也没有处理的了异常, 就继续向上传递.<br>         7. 一直到 main 方法也没有合适的代码处理异常, 就会交给 JVM 来进行处理, 此时程序就会异常终止.</strong></p> 
</blockquote> 
<p></p> 
<p></p> 
<h2 id="5.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8"><span style="color:#956fe7;">5.自定义异常</span></h2> 
<p><strong>说到自定义异常，我们首先要了解一下什么是自定义异常：</strong></p> 
<blockquote> 
 <p>      <span style="color:#ff9900;"><strong>  自定义异常是指由开发人员根据实际需求创建的异常类，它们扩展自Java标准库中的Exception或其子类。与标准异常类不同，自定义异常类可以提供更具体的异常信息、更详细的上下文信息，以及针对特定业务逻辑的错误处理逻辑。</strong></span></p> 
</blockquote> 
<p><strong>了解完了什么是自定义异常之后，先让我们看一下如何去创建一个自定义异常。</strong></p> 
<p>创建一个自定义异常类，方式如下：</p> 
<blockquote> 
 <p><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>1. 自定义异常类，然后继承自Exception 或者 RunTimeException</strong></span><br><span style="color:#ff9900;"><strong>        </strong></span><span style="color:#ff9900;"><strong>2. 实现一个带有String类型参数的构造方法，参数含义：出现异常的原因</strong></span></p> 
</blockquote> 
<p><span style="color:#ffd900;"><strong>例子：</strong></span></p> 
<pre><code class="language-java">// 自定义运行时异常类
class InvalidAgeException extends RuntimeException {
    // 无参构造方法
    public InvalidAgeException() {
        super("年龄无效");
    }

    // 带有异常消息的构造方法
    public InvalidAgeException(String message) {
        super(message);
    }
}</code></pre> 
<p><strong>        这样我们就创建好了一个自定义异常了，那么自定义异常创建好之后，我们又该如何的使用它呢？让我们继续往下看！</strong></p> 
<p>现在我们将要使用刚才创建好的自定义异常类来完成一个小案例：（代码如下）</p> 
<pre><code class="language-java">// 创建人类
class Person {
    private String name;
    private int age;

    // 构造方法
    public Person(String name, int age) {
        this.name = name;
        // 检查年龄是否有效，如果无效则抛出自定义异常
        if (age &lt; 0 || age &gt; 150) {
            //使用了我们刚才创建的自定义异常类
            throw new InvalidAgeException("年龄必须在0到150之间");
        }
        this.age = age;
    }

    // 获取年龄
    public int getAge() {
        return age;
    }
}

//测试类
public class CustomRuntimeExceptionExample {
    public static void main(String[] args) {
        // 创建一个人类对象，年龄为负数，会抛出自定义异常
        try {
            Person person = new Person("Alice", -10);
            System.out.println(person.getAge());
        } catch (InvalidAgeException e) {
            // 捕获并处理自定义异常
            System.err.println("创建人物失败：" + e.getMessage());
        }

        // 创建一个人类对象，年龄超过有效范围，也会抛出自定义异常
        try {
            Person person = new Person("Bob", 160);
            System.out.println(person.getAge());
        } catch (InvalidAgeException e) {
            // 捕获并处理自定义异常
            System.err.println("创建人物失败：" + e.getMessage());
        }
    }
}</code></pre> 
<p>       <strong> 在上面的代码中，我们首先定义了一个名为InvalidAgeException的自定义异常类，它继承自RuntimeException类。然后我们定义了一个Person类，其中包含一个构造方法用于创建人类对象，并在构造方法中检查年龄是否有效。如果年龄无效，则抛出InvalidAgeException异常。</strong></p> 
<p><strong>        然后在main方法中，我们分别创建了两个Person对象，一个年龄为负数，一个年龄超过有效范围。在创建这两个对象时，都会抛出自定义异常。我们使用try-catch语句块捕获并处理这些异常，输出错误信息到控制台。</strong></p> 
<p><strong>        <span style="color:#a2e043;">通过这个案例我相信读者你已经大致的了解了如何创建一个自定义异常类和如何去使用创建的自定义异常类了。</span></strong></p> 
<p><span style="color:#fe2c24;"><strong>注意事项：</strong></span></p> 
<blockquote> 
 <p><span style="color:#fe2c24;"><strong>1. 自定义异常通常会继承自 Exception 或者 RuntimeException<br> 2. 继承自 Exception 的异常默认是受查异常<br> 3. 继承自 RuntimeException 的异常默认是非受查异常.</strong></span></p> 
</blockquote> 
<p>这样我们就了解了Java中自定义异常了。</p> 
<p></p> 
<hr> 
<p style="text-align:center;"><span style="color:#38d8f0;"><strong>以上就是本篇文章的所以内容了~~~</strong></span></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/0a22b7da9cbcd0425d6e7ed8f9141102/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">TON DeFi 生态：探索创新与发展轨迹</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/c1d51767b16fbba5a4d7a596bf26b396/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">Mac Typora 破解</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>